version: 2
# https://circleci.com/docs/configuration#machine
jobs:
    build:
        docker:
            - image: stevector/pantheon_advanced_page_cache
        working_directory: ~/pantheon_advanced_page_cache
        environment:

            BASH_ENV: ~/.bashrc
            TZ: "/usr/share/zoneinfo/America/Los_Angeles"

        steps:

            - run:
                name: login-pantheon
                command: terminus auth:login -n --machine-token="$TERMINUS_TOKEN"
            - run:
                name: whoami
                command: terminus auth:whoami
            - run:
                name: list
                command: terminus list


            # - run:
            #     name: login-pantheon
            #     command: terminus multidev:create $TERMINUS_SITE.asdf
