version: 2
# https://circleci.com/docs/configuration#machine
jobs:
    build:
        docker:
            - image: stevector/pantheon_advanced_page_cache
        working_directory: ~/pantheon_advanced_page_cache
        environment:

            BASH_ENV: ~/.bashrc
            TZ: "/usr/share/zoneinfo/America/Los_Angeles"
            TERMINUS_SITE: d8cdn
            TERMINUS_ENV: ci-${CIRCLE_BUILD_NUM}

        steps:
            - checkout
            - restore_cache:
                key: dependency-cache-{{ checksum "composer.lock" }}
            - run:
                name: Composer install
                command: |
                  pwd
                  ls
                  composer install
            - save_cache:
                key: dependency-cache-{{ checksum "composer.lock" }}
                paths:
                  - ~/.composer/cache
            - run:
                name: PHP Code Sniff
                command: composer codesniff
            - run:
                name: login-pantheon
                command: |
                  terminus auth:login -n --machine-token="$TERMINUS_TOKEN"
            - run:
                name: make-multidev
                command: |
                  touch $HOME/.ssh/config
                  echo "StrictHostKeyChecking no" >> "$HOME/.ssh/config"
                  terminus env:create $TERMINUS_SITE.dev ${TERMINUS_ENV}
                  terminus connection:set ${TERMINUS_SITE}.${TERMINUS_ENV} sftp
                  terminus drush ${TERMINUS_SITE}.${TERMINUS_ENV} -- site-install -y
                  terminus drush ${TERMINUS_SITE}.${TERMINUS_ENV} -- cset system.performance cache.page.max_age 600 -y
            - run:
                name: Composer require
                command: |
                  terminus composer ${TERMINUS_SITE}.${TERMINUS_ENV} -- config repositories.papc vcs git@github.com:pantheon-systems/pantheon_advanced_page_cache.git
                  terminus composer ${TERMINUS_SITE}.${TERMINUS_ENV} -- require drupal/pantheon_advanced_page_cache:dev-8.x-1.x#$CIRCLE_SHA1





          # Run PHP code sniff
          # Run Behat tests
