version: 2
# https://circleci.com/docs/configuration#machine
jobs:
    build:
        docker:
            - image: stevector/pantheon_advanced_page_cache
        working_directory: ~/pantheon_advanced_page_cache
        environment:

            BASH_ENV: ~/.bashrc
            TZ: "/usr/share/zoneinfo/America/Los_Angeles"

        steps:
            - run:
                name: login-pantheon
                command: |
                  terminus auth:login -n --machine-token="$TERMINUS_TOKEN"
                  terminus auth:whoami
                  terminus list
            - run:
                name: make-multidev
                command: |
                  terminus multidev:create ${TERMINUS_SITE}.dev ${CIRCLE_BUILD_NUM} --yes
                  terminus connection:set ${TERMINUS_SITE}.${CIRCLE_BUILD_NUM} sftp
            - run:
                name: Enable anonymous caching
                command:  terminus drush ${TERMINUS_SITE}.${CIRCLE_BUILD_NUM} -- cset system.performance cache.page.max_age 600 -y
            - run:
                name: Composer require
                command: |
                  terminus composer ${TERMINUS_SITE}.${CIRCLE_BUILD_NUM} -- config repositories.papc vcs git@github.com:pantheon-systems/pantheon_advanced_page_cache.git
                  terminus composer ${TERMINUS_SITE}.${CIRCLE_BUILD_NUM} -- require drupal/pantheon_advanced_page_cache:dev-8.x-1.x#$CIRCLE_SHA1
